/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { OTS } from "./OTS";
export * as factories from "./factories";
export { OTS__factory } from "./factories/OTS__factory";
